language: python

before_install:
  - sudo apt-get install glpk-utils libglpk-dev
install:
  - pip install pyomo
  
script:
  - glpsol -m OSeMOSYS_GNU_MathProg/osemosys.txt -d Training_Case_Studies/utopia.txt -o results.csv
  - pyomo solve --solver=glpk OSeMOSYS_Python/OSeMOSYS-Pyomo_2019_05_13.py OSeMOSYS_Python/UTOPIA_2015_08_27.dat